<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-AJRJQFP7" ignored="0" name="Test" tests="8" failures="4" timestamp="16 Jun 2020 11:28:50 GMT" time="0.131" errors="0">
  <testcase name="tc11" time="0.032" classname="org.parallel.execution.B"/>
  <testcase name="tc1" time="0.032" classname="org.parallel.execution.A"/>
  <testcase name="tc12" time="0.008" classname="org.parallel.execution.B">
    <failure type="java.lang.AssertionError" message="The Test case 2 gets failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The Test case 2 gets failed expected [true] but found [false]
	at org.parallel.execution.B.tc12(B.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc12 -->
  <testcase name="tc2" time="0.008" classname="org.parallel.execution.A">
    <failure type="java.lang.AssertionError" message="The Test case 2 gets failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The Test case 2 gets failed expected [true] but found [false]
	at org.parallel.execution.A.tc2(A.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc13" time="0.0" classname="org.parallel.execution.B"/>
  <testcase name="tc3" time="0.008" classname="org.parallel.execution.A"/>
  <testcase name="tc14" time="0.0" classname="org.parallel.execution.B">
    <failure type="java.lang.AssertionError" message="The Test case 4 gets failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The Test case 4 gets failed expected [true] but found [false]
	at org.parallel.execution.B.tc14(B.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc14 -->
  <testcase name="tc4" time="0.0" classname="org.parallel.execution.A">
    <failure type="java.lang.AssertionError" message="The Test case 4 gets failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The Test case 4 gets failed expected [true] but found [false]
	at org.parallel.execution.A.tc4(A.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc4 -->
</testsuite> <!-- Test -->
